### ISSUE TITLE
Day 4 IR_SmartLights does not compile

### ISSUE THREAD

**Issue by sricheson** [inventrdotio/AdventureKit2#16]
IR_SmartLights does not compile.
(Need a _break;_ statement between lines 96 and 97 for the _default:_ case.)

**Comment by inetdavid** [comment]
I'm working on this now, Sue.  I've re-done the Fritzing and did the quick fix for the code, though the code needs a lot more cleanup.  When I duplicated the circuit I noticed that when the red LED was on the blue didn't seem to make any change in color, even though the blue worked fine by itself.  I modified the circuit to place the 220 ohm resistors on each color rather than the common ground and then I was able to get "purple" using both red and blue.

I'll probably make this into a three sketch solution.  First sketch will read the IR code and display it to the serial console so that the buttons can be identified.  The second sketch will be like the current one, turning each color on/off.  For the third I thought perhaps I'd modify it so that each "up" code would increase the intensity of that color and each down would reduce the intensity.

Let me know your thoughts.  I wanted to give you some quick feedback to let you know it's being worked on.

**Comment by sricheson** [comment]
Yes, I saw that I was not able to get blended colors also, so I dropped back to the component instructions for RGB LED and used the 3 resistors. 

All worked well then.

 

I’m an ‘old hand’ retired from 40 years of firmware and software development.  So I do these things for entertainment.  But it might be 

hard for a middle or high schooler unfamiliar with electronics and software to figure some of this stuff out by troubleshooting.  That’s the

one thing I would recommend keeping in mind.

 

Going with a stepped approach is probably good.  That’s leads them to get the codes from the remote so they can use them in the later sketch.

Again, I collected those codes first thing with the instructions for just the IR and remote components.  (Interestingly they matched up with 

another remote I’d gotten with a Hackerbox.)

 

Anyway, I think that stepped approach is the best for those just learning.

 

I’ll try out the new code when it’s posted.

 

Sue

**Comment by inetdavid** [comment]
Yup, I'm a recently retired Sr. Software Engineer and when I played with the Adventure Kit I just had to start updating the code and sending it to the guys.  They insisted on paying me (first in parts/pieces/kits) and now I'm back to working 20 hours/week (my limit).  I just pushed up the first of the three sketches.  This one does the command decodes and has a structure to add descriptions for recognized commands.  Feel free to be VERY critical of code/comments.  Goal is to be clear  and good learning.

**Comment by inetdavid** [comment]
OK, more re-writing.  Broke it into FOUR sketches, and I'm using ENUMS so I don't have to repeat the command codes in multiple places.  Final sketch uses PWM to be able to change each color intensity in steps (which requires moving to different pins).  Alex says he may just use the last sketch as we're so overloaded right now, but I still want the steps showing.

Check out the different versions and let me know what you think.

**Comment by sricheson** [comment]
I’ll check the sketches out Monday afternoon.

Thanks for reworking.  

Keep middle and high schoolers as the target unless the target of Inventr.io is more experienced than that.

sue
